enum Professions {
    Teacher,
    Scientist,
    Trader,
    Gardener,
    Plumber,
    Pilot,
    Engineer,
    Driver,
    FactoryEmployee,
    Veterinarian,
    SoftwareDeveloper,
    SystemAdministrator,
    FilmDirector,
    Lawyer,
    Judge,
    Chemist,
    Architext,
    Farmer,
    Lobbyist,
    Bartender,
    Cook,
    Hairdresser,
    FireFighter,
    PoliceOfficer,
    Cashier,
    SalesPerson,
    Hunter,
    GarbageCollector,  // This is a funny one.
    Manager,
};

enum MaritalStatus {
    Single,
    Maried,
    Separated,
    Divorced,
    Widowed,
};
